[[benchmarks]]
name = "4apx_n10_m20"
benchmark = "random_graphs"
approximate_algorithm = "4apx"
n = 10
m = 20
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "4apx_n10_m30"
benchmark = "random_graphs"
approximate_algorithm = "4apx"
n = 10
m = 30
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "4apx_n10_m40"
benchmark = "random_graphs"
approximate_algorithm = "4apx"
n = 10
m = 40
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "4apx_n15_m20"
benchmark = "random_graphs"
approximate_algorithm = "4apx"
n = 15
m = 20
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "4apx_n15_m30"
benchmark = "random_graphs"
approximate_algorithm = "4apx"
n = 15
m = 30
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "4apx_n15_m40"
benchmark = "random_graphs"
approximate_algorithm = "4apx"
n = 15
m = 40
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "4apx_n20_m20"
benchmark = "random_graphs"
approximate_algorithm = "4apx"
n = 20
m = 20
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "4apx_n20_m30"
benchmark = "random_graphs"
approximate_algorithm = "4apx"
n = 20
m = 30
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "4apx_n20_m40"
benchmark = "random_graphs"
approximate_algorithm = "4apx"
n = 20
m = 40
num_iterations = 100
bitset = true
seed = 42
