[[benchmarks]]
name = "mf_n10_m20"
benchmark = "random_graphs"
approximate_algorithm = "mf"
n = 10
m = 20
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mf_n10_m30"
benchmark = "random_graphs"
approximate_algorithm = "mf"
n = 10
m = 30
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mf_n10_m40"
benchmark = "random_graphs"
approximate_algorithm = "mf"
n = 10
m = 40
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mf_n15_m20"
benchmark = "random_graphs"
approximate_algorithm = "mf"
n = 15
m = 20
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mf_n15_m30"
benchmark = "random_graphs"
approximate_algorithm = "mf"
n = 15
m = 30
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mf_n15_m40"
benchmark = "random_graphs"
approximate_algorithm = "mf"
n = 15
m = 40
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mf_n20_m20"
benchmark = "random_graphs"
approximate_algorithm = "mf"
n = 20
m = 20
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mf_n20_m30"
benchmark = "random_graphs"
approximate_algorithm = "mf"
n = 20
m = 30
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mf_n20_m40"
benchmark = "random_graphs"
approximate_algorithm = "mf"
n = 20
m = 40
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "md_n10_m20"
benchmark = "random_graphs"
approximate_algorithm = "md"
n = 10
m = 20
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "md_n10_m30"
benchmark = "random_graphs"
approximate_algorithm = "md"
n = 10
m = 30
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "md_n10_m40"
benchmark = "random_graphs"
approximate_algorithm = "md"
n = 10
m = 40
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "md_n15_m20"
benchmark = "random_graphs"
approximate_algorithm = "md"
n = 15
m = 20
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "md_n15_m30"
benchmark = "random_graphs"
approximate_algorithm = "md"
n = 15
m = 30
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "md_n15_m40"
benchmark = "random_graphs"
approximate_algorithm = "md"
n = 15
m = 40
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "md_n20_m20"
benchmark = "random_graphs"
approximate_algorithm = "md"
n = 20
m = 20
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "md_n20_m30"
benchmark = "random_graphs"
approximate_algorithm = "md"
n = 20
m = 30
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "md_n20_m40"
benchmark = "random_graphs"
approximate_algorithm = "md"
n = 20
m = 40
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mdpf_n10_m20"
benchmark = "random_graphs"
approximate_algorithm = "mdpf"
n = 10
m = 20
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mdpf_n10_m30"
benchmark = "random_graphs"
approximate_algorithm = "mdpf"
n = 10
m = 30
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mdpf_n10_m40"
benchmark = "random_graphs"
approximate_algorithm = "mdpf"
n = 10
m = 40
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mdpf_n15_m20"
benchmark = "random_graphs"
approximate_algorithm = "mdpf"
n = 15
m = 20
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mdpf_n15_m30"
benchmark = "random_graphs"
approximate_algorithm = "mdpf"
n = 15
m = 30
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mdpf_n15_m40"
benchmark = "random_graphs"
approximate_algorithm = "mdpf"
n = 15
m = 40
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mdpf_n20_m20"
benchmark = "random_graphs"
approximate_algorithm = "mdpf"
n = 20
m = 20
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mdpf_n20_m30"
benchmark = "random_graphs"
approximate_algorithm = "mdpf"
n = 20
m = 30
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mdpf_n20_m40"
benchmark = "random_graphs"
approximate_algorithm = "mdpf"
n = 20
m = 40
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mss_n10_m20"
benchmark = "random_graphs"
approximate_algorithm = "mss"
n = 10
m = 20
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mss_n10_m30"
benchmark = "random_graphs"
approximate_algorithm = "mss"
n = 10
m = 30
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mss_n10_m40"
benchmark = "random_graphs"
approximate_algorithm = "mss"
n = 10
m = 40
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mss_n15_m20"
benchmark = "random_graphs"
approximate_algorithm = "mss"
n = 15
m = 20
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mss_n15_m30"
benchmark = "random_graphs"
approximate_algorithm = "mss"
n = 15
m = 30
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mss_n15_m40"
benchmark = "random_graphs"
approximate_algorithm = "mss"
n = 15
m = 40
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mss_n20_m20"
benchmark = "random_graphs"
approximate_algorithm = "mss"
n = 20
m = 20
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mss_n20_m30"
benchmark = "random_graphs"
approximate_algorithm = "mss"
n = 20
m = 30
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mss_n20_m40"
benchmark = "random_graphs"
approximate_algorithm = "mss"
n = 20
m = 40
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mfd_n10_m20"
benchmark = "random_graphs"
approximate_algorithm = "mfd"
n = 10
m = 20
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mfd_n10_m30"
benchmark = "random_graphs"
approximate_algorithm = "mfd"
n = 10
m = 30
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mfd_n10_m40"
benchmark = "random_graphs"
approximate_algorithm = "mfd"
n = 10
m = 40
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mfd_n15_m20"
benchmark = "random_graphs"
approximate_algorithm = "mfd"
n = 15
m = 20
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mfd_n15_m30"
benchmark = "random_graphs"
approximate_algorithm = "mfd"
n = 15
m = 30
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mfd_n15_m40"
benchmark = "random_graphs"
approximate_algorithm = "mfd"
n = 15
m = 40
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mfd_n20_m20"
benchmark = "random_graphs"
approximate_algorithm = "mfd"
n = 20
m = 20
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mfd_n20_m30"
benchmark = "random_graphs"
approximate_algorithm = "mfd"
n = 20
m = 30
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mfd_n20_m40"
benchmark = "random_graphs"
approximate_algorithm = "mfd"
n = 20
m = 40
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mdf_n10_m20"
benchmark = "random_graphs"
approximate_algorithm = "mdf"
n = 10
m = 20
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mdf_n10_m30"
benchmark = "random_graphs"
approximate_algorithm = "mdf"
n = 10
m = 30
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mdf_n10_m40"
benchmark = "random_graphs"
approximate_algorithm = "mdf"
n = 10
m = 40
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mdf_n15_m20"
benchmark = "random_graphs"
approximate_algorithm = "mdf"
n = 15
m = 20
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mdf_n15_m30"
benchmark = "random_graphs"
approximate_algorithm = "mdf"
n = 15
m = 30
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mdf_n15_m40"
benchmark = "random_graphs"
approximate_algorithm = "mdf"
n = 15
m = 40
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mdf_n20_m20"
benchmark = "random_graphs"
approximate_algorithm = "mdf"
n = 20
m = 20
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mdf_n20_m30"
benchmark = "random_graphs"
approximate_algorithm = "mdf"
n = 20
m = 30
num_iterations = 100
bitset = true
seed = 42

[[benchmarks]]
name = "mdf_n20_m40"
benchmark = "random_graphs"
approximate_algorithm = "mdf"
n = 20
m = 40
num_iterations = 100
bitset = true
seed = 42
